<a href="https://colab.research.google.com/github/fralfaro/MAT281_2022/blob/main/labs/lab_07/lab_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MAT281 - Laboratorio N°07


<a id='p1'></a>
## I.- Problema 01


<img src="https://www.cardrates.com/wp-content/uploads/2020/08/shutterstock_576998230.jpg?1" width="480" height="360" align="center"/>


El conjunto de datos se denomina `creditcard.csv` y consta de varias columnas con información acerca del fraude de tarjetas de crédito, en donde la columna **Class** corresponde a: 0 si no es un fraude y 1 si es un fraude.

En este ejercicio se trabajará el problemas de  clases desbalancedas. Veamos las primeras cinco filas dle conjunto de datos:

In [13]:
#Importar librerias, modelos y méticas.
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import datasets
from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

%matplotlib inline
sns.set_palette("deep", desat=.6)
sns.set(rc={'figure.figsize':(11.7,8.27)})

In [3]:
# cargar datos
df = pd.read_csv("https://raw.githubusercontent.com/fralfaro/MAT281_2022/main/labs/lab_07/data/creditcard.csv",sep=';')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   4.0  1.229658  0.141004  0.045371  1.202613  0.191881  0.272708 -0.005159   
2  10.0  1.249999 -1.221637  0.383930 -1.234899 -1.485419 -0.753230 -0.689405   
3  10.0  0.384978  0.616109 -0.874300 -0.094019  2.924584  3.317027  0.470455   
4  12.0  1.103215 -0.040296  1.267332  1.289091 -0.735997  0.288069 -0.586057   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.081213  0.464960  ... -0.167716 -0.270710 -0.154104 -0.780055  0.750137   
2 -0.227487 -2.094011  ... -0.231809 -0.483285  0.084668  0.392831  0.161135   
3  0.538247 -0.558895  ...  0.049924  0.238422  0.009130  0.996710 -0.767315   
4  0.189380  0.782333  ... -0.024612  0.196002  0.013802  0.103758  0.364298   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1 -0.257237  0.034507  0.005168    4.99      0  
2 -0.354990  0.026416  0.042422  121.50      0  
3 -0.492208  0.042472 -0.054337    9.99      0  
4 -0.382261  0.092809  0.037051   12.99      0  

[5 rows x 31 columns]

Analicemos el total de fraudes respecto a los casos que nos son fraudes:


In [12]:
#DataFrame con cantidades y proporciones de fraudes y no fraudes.
#Crear Dataframe df_count vacio.
df_count = pd.DataFrame()
#Definir columnas del DataFrame df_count.
df_count["fraude"] =["no","si"]
df_count["total"] = df["Class"].value_counts() 
df_count["porcentaje"] = 100*df_count["total"] /df_count["total"] .sum()
# Mostrar df_count
df_count

fraude  total  porcentaje
0     no  50000   99.025588
1     si    492    0.974412

Se observa que menos del 1% corresponde a registros frudulentos. La pregunta que surgen son:

* ¿ Cómo deben ser el conjunto de entrenamiento y de testeo?
* ¿ Qué modelos ocupar?
* ¿ Qué métricas ocupar?

Por ejemplo, analicemos el modelos de regresión logística y apliquemos el procedimiento estándar:

In [7]:
# datos 
y = df.Class
X = df.drop('Class', axis=1)
# split o separar dataset en conjuntos test y entrenamiento.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=27)
# Creando el modelo y ajustando el modelo a los datos de entrenamiento.
lr = LogisticRegression(solver='liblinear').fit(X_train, y_train) 
# predecir 
lr_pred = lr.predict(X_test)
# calcular accuracy
accuracy_score(y_test, lr_pred)

0.9961181969420898

En general el modelo tiene un **accuracy** del 99,9%, es decir, un podría suponer que el modelo predice casi perfectamente, pero eso esta lejos de ser así.  Para ver por qué es necesario seguir los siguientes pasos:

### 1. Cambiar la métrica de rendimiento

El primer paso es comparar con distintas métricas, para eso ocupemos las 4 métricas clásicas abordadas en el curso:
* accuracy
* precision
* recall
* f-score

En este punto deberá poner las métricas correspondientes y comentar sus resultados.

In [8]:
# metrics
#Lista con datos de testeo.
y_true_1 =  list(y_test)
#Lista con datos que predice el modelo.
y_pred_1 = list(lr.predict(X_test))
#Matriz de confusión.
print('\nMatriz de confusion:\n ')
print(confusion_matrix(y_true_1,y_pred_1))
print('\nMetricas:\n ')
# Aplicar distintas métricas a los datos de testeo y que predijo el modelo.
print('accuracy:   ',accuracy_score(y_test, lr_pred))
print('recall:     ',recall_score(y_test, lr_pred))
print('precision:  ',precision_score(y_test, lr_pred))
print('f-score:    ',f1_score(y_test, lr_pred))
print("")# Imprimir resultados.


Matriz de confusion:
 
[[12471    16]
 [   33   103]]

Metricas:
 
accuracy:    0.9961181969420898
recall:      0.7573529411764706
precision:   0.865546218487395
f-score:     0.807843137254902



In [11]:
# Crear DataFrame df_result_1 con las métricas de LogisticRegression. 
#DataFrame vacio.
df_result_1 = pd.DataFrame()
#Definir columnas del DataFrame.
df_result_1['accuracy'] = [accuracy_score(y_true_1,y_pred_1)]
df_result_1['recall'] = [recall_score(y_true_1,y_pred_1)]
df_result_1['precision'] = [precision_score(y_true_1,y_pred_1)]
df_result_1['fscore'] = [f1_score(y_true_1,y_pred_1)]
df_result_1['modelo'] = ['LogisticRegression']
df_result_1#Mostrar DataFrame.

accuracy    recall  precision    fscore              modelo
0  0.996118  0.757353   0.865546  0.807843  LogisticRegression

Según las métricas podemos concluir que con este modelo se consigue: 
* (accuracy) Un porcentaje casi total de predicciones correctas frente al total de predicciones.
* (recall) Una proporción apenas aceptable de casos positivos bien clasificados por el modelo, respecto al total de positivos, o mejor dicho,  una habilidad aceptable del modelo para detectar los casos relevantes.
* (precision) La mayoria de resultado de predicciones cercanos al valor verdadero.
* (f-score) Una buena precisión de test.


### 2. Cambiar algoritmo

El segundo paso es comparar con distintos modelos. Debe tener en cuenta que el modelo ocupaod resuelva el problema supervisado de clasificación.

En este punto deberá ajustar un modelo de **random forest**, aplicar las métricas y comparar con el modelo de regresión logística.

In [10]:
#Entrenar modelo Random Forest.
rfc = RandomForestClassifier(max_depth=None, n_estimators=100, max_features="sqrt").fit(X_train, y_train) # algoritmo random forest

In [14]:
# metrics
#Lista con datos de testeo.
y_true_2 =  list(y_test)
#Lista con datos que predice el modelo.
y_pred_2 = list(rfc.predict(X_test)) # predicciones con random forest
#Matriz de confusión.
print('\nMatriz de confusion:\n ')
print(confusion_matrix(y_true_2,y_pred_2))
# Aplicar distintas métricas a los datos de testeo y que predijo el modelo.
print('\nMetricas:\n ')
print('accuracy:   ',accuracy_score(y_true_2,y_pred_2))
print('recall:     ',recall_score(y_true_2,y_pred_2))
print('precision:  ',precision_score(y_true_2,y_pred_2))
print('f-score:    ',f1_score(y_true_2,y_pred_2))
print("")# Imprimir resultados.


Matriz de confusion:
 
[[12484     3]
 [   25   111]]

Metricas:
 
accuracy:    0.9977818268240514
recall:      0.8161764705882353
precision:   0.9736842105263158
f-score:     0.888



In [15]:
# Crear DataFrame df_result_2 con las métricas de RandomForest. 
#DataFrame vacio.
df_result_2 = pd.DataFrame()
#Definir columnas del DataFrame.
df_result_2['accuracy'] = [accuracy_score(y_true_2,y_pred_2)]
df_result_2['recall'] = [recall_score(y_true_2,y_pred_2)]
df_result_2['precision'] = [precision_score(y_true_2,y_pred_2)]
df_result_2['fscore'] = [f1_score(y_true_2,y_pred_2)]
df_result_2['modelo'] = ['RandomForest']
df_result_2#Mostrar DataFrame.

accuracy    recall  precision  fscore        modelo
0  0.997782  0.816176   0.973684   0.888  RandomForest

Según estas métricas podemos ver que, a diferencia del anterior modelo, con este modelo se consigue: 

* (accuracy o exactitud) Subio en 0,17% el total de predicciones correctas frente al total de predicciones.
* (recall o sensibilidad) Subio en 5,88% la proporción de casos positivos bien clasificados por el modelo, respecto al total de positivos, o mejor dicho, la habilidad del modelo para detectar los casos relevantes.
* (precision o presiciòn) Subio en 10,81% los resultado de predicciones cercanos al valor verdadero.
* (f-score) Subio en 8,02% la precisión de test.

Todas las métricas tuvieron un porcentaje de subida con el modelo Random Forest.

### 3. Técnicas de remuestreo: sobremuestreo de clase minoritaria

El tercer paso es ocupar ténicas de remuestreo, pero sobre la clase minoritaria. Esto significa que mediantes ténicas de remuestreo trataremos de equiparar el número de elementos de la clase minoritaria a la clase mayoritaria.

In [17]:
from sklearn.utils import resample
# concatenar el conjunto de entrenamiento
X = pd.concat([X_train, y_train], axis=1)
# separar las clases
not_fraud = X[X.Class==0]
fraud = X[X.Class==1]
# remuestrear  clase minoritaria
fraud_upsampled = resample(fraud,
                          replace=True, # sample with replacement
                          n_samples=len(not_fraud), # match number in majority class
                          random_state=27) # reproducible results
# recombinar resultados
upsampled = pd.concat([not_fraud, fraud_upsampled])
# chequear el número de elementos por clases
upsampled.Class.value_counts()# Cantidad de elementos por clase.

0    37513
1    37513
Name: Class, dtype: int64

In [18]:
# datos de entrenamiento sobre-balanceados
y_train = upsampled.Class
X_train = upsampled.drop('Class', axis=1)

Ocupando estos nuevos conjunto de entrenamientos, vuelva a aplicar el modelos de regresión logística y calcule las correspondientes métricas. Además, justifique las ventajas y desventjas de este procedimiento.

In [19]:
#Entrenar modelo con nuevos datos.
upsampled = LogisticRegression(solver='liblinear').fit(X_train, y_train) # algoritmo de regresion logistica
# metrics
#Lista con datos de testeo.
y_true_3 =  list(y_test)
#Lista con datos que predice el modelo.
y_pred_3 = list(upsampled.predict(X_test))
#Matriz de confusión.
print('\nMatriz de confusion:\n ')
print(confusion_matrix(y_true_3,y_pred_3))
# Aplicar distintas métricas a los datos de testeo y que predijo el modelo.
print('\nMetricas:\n ')
print('accuracy:   ',accuracy_score(y_true_3,y_pred_3))
print('recall:     ',recall_score(y_true_3,y_pred_3))
print('precision:  ',precision_score(y_true_3,y_pred_3))
print('f-score:    ',f1_score(y_true_3,y_pred_3))
print("")# Imprimir resultados.


Matriz de confusion:
 
[[12200   287]
 [   12   124]]

Metricas:
 
accuracy:    0.976313079299691
recall:      0.9117647058823529
precision:   0.30170316301703165
f-score:     0.45338208409506403



In [20]:
# Crear DataFrame df_result_3 con las métricas de LogisticRegression Sobre-balanceado. 
#DataFrame vacio.
df_result_3 = pd.DataFrame()
#Definir columnas del DataFrame.
df_result_3['accuracy'] = [accuracy_score(y_true_3,y_pred_3)]
df_result_3['recall'] = [recall_score(y_true_3,y_pred_3)]
df_result_3['precision'] = [precision_score(y_true_3,y_pred_3)]
df_result_3['fscore'] = [f1_score(y_true_3,y_pred_3)]
df_result_3['modelo'] = ['LogisticRegression_Sobre-balanceado']
df_result_3#Mostrar DataFrame.

accuracy    recall  precision    fscore  \
0  0.976313  0.911765   0.301703  0.453382   

                                modelo  
0  LogisticRegression_Sobre-balanceado

Según las métricas de este modelo agustado podemos comparar que: 
* (accuracy o exactitud) Bajo en 1,98% el total de predicciones correctas frente al total de predicciones.
* (recall o sensibilidad) Subio en 15,44% la proporción de casos positivos bien clasificados por el modelo, respecto al total de positivos, o mejor dicho, la habilidad del modelo para detectar los casos relevantes.
* (precision o presiciòn) Bajo en 56,38% los resultado de predicciones cercanos al valor verdadero.
* (f-score) Bajo en 35,45% la precisión de test.

Entonces, se puede ver que sobre-abalancear los datos mejorò la sensibilidad y que la exactitud bajo infimamente. Sin embargo, se perdió precisión en gran medida y f_score empeoró.   

### 4. Técnicas de remuestreo - Ejemplo de clase mayoritaria

El cuarto paso es ocupar ténicas de remuestreo, pero sobre la clase mayoritaria. Esto significa que mediantes ténicas de remuestreo trataremos de equiparar el número de elementos de la clase mayoritaria  a la clase minoritaria.

In [21]:
# remuestreo clase mayoritaria
not_fraud_downsampled = resample(not_fraud,
                                replace = False, # sample without replacement
                                n_samples = len(fraud), # match minority n
                                random_state = 27) # reproducible results
# recombinar resultados
downsampled = pd.concat([not_fraud_downsampled, fraud])
# chequear el número de elementos por clases
downsampled.Class.value_counts()# Cantidad de elementos por clase.

0    356
1    356
Name: Class, dtype: int64

In [22]:
# datos de entrenamiento sub-balanceados
y_train_1 = downsampled.Class
X_train_1 = downsampled.drop('Class', axis=1)

Ocupando estos nuevos conjunto de entrenamientos, vuelva a aplicar el modelos de regresión logística y calcule las correspondientes métricas. Además, justifique las ventajas y desventjas de este procedimiento.

In [23]:
#Entrenar modelo con nuevos datos.
undersampled = LogisticRegression(solver='liblinear').fit(X_train, y_train) # modelo de regresi+on logística
# metrics
#Lista con datos de testeo.
y_true_4 =  list(y_test)
#Lista con datos que predice el modelo.
y_pred_4 = list(undersampled.predict(X_test))
#Matriz de confusión.
print('\nMatriz de confusion:\n ')
print(confusion_matrix(y_true_4,y_pred_4))
# Aplicar distintas métricas a los datos de testeo y los que predijo el modelo.
print('\nMetricas:\n ')
print('accuracy:   ',accuracy_score(y_true_4,y_pred_4))
print('recall:     ',recall_score(y_true_4,y_pred_4))
print('precision:  ',precision_score(y_true_4,y_pred_4))
print('f-score:    ',f1_score(y_true_4,y_pred_4))
print("")# Imprimir resultados.


Matriz de confusion:
 
[[12200   287]
 [   12   124]]

Metricas:
 
accuracy:    0.976313079299691
recall:      0.9117647058823529
precision:   0.30170316301703165
f-score:     0.45338208409506403



In [24]:
# Crear DataFrame df_result_4 con las métricas de LogisticRegression Sub-balanceado. 
#DataFrame vacio.
df_result_4 = pd.DataFrame()
#Definir columnas del DataFrame.
df_result_4['accuracy'] = [accuracy_score(y_true_4,y_pred_4)]
df_result_4['recall'] = [recall_score(y_true_4,y_pred_4)]
df_result_4['precision'] = [precision_score(y_true_4,y_pred_4)]
df_result_4['fscore'] = [f1_score(y_true_4,y_pred_4)]
df_result_4['modelo'] = ['LogisticRegression_Sub-balanceado']
df_result_4#Mostrar DataFrame.

accuracy    recall  precision    fscore                             modelo
0  0.976313  0.911765   0.301703  0.453382  LogisticRegression_Sub-balanceado

Según las métricas de este modelo agustado podemos comparar que: 
* (accuracy o exactitud) Bajo en 1,98% el total de predicciones correctas frente al total de predicciones.
* (recall o sensibilidad) Subio en 15,44% la proporción de casos positivos bien clasificados por el modelo, respecto al total de positivos, o mejor dicho, la habilidad del modelo para detectar los casos relevantes.
* (precision o presiciòn) Bajo en 56,38% los resultado de predicciones cercanos al valor verdadero.
* (f-score) Bajo en 35,45% la precisión de test.

Entonces, se puede ver que sub-balancear los datos mejoró la sensibilidad y que la exactitud bajo infimamente. Sin embargo, se perdió precisión en gran medida y f_score empeoró.



### 5. Conclusiones

Para finalizar el laboratorio, debe realizar un análisis comparativo con los disintos resultados obtenidos  en los pasos 1-4. Saque sus propias conclusiones del caso.

In [25]:
#Creaar DataFrame resumen llamado result.
#Crear lista de los DataFrames creados en cada uno de los pasos.
frames = [df_result_1, df_result_2, df_result_3, df_result_4]
#Concatenar los cuatro DataFrames
result = pd.concat(frames)
#Ordenar los valores de forma descendente en cada una de las columnas.
result.sort_values(by=['accuracy','recall','precision','fscore'], inplace=True, ascending=False)
#Reiniciar el indice.
result.reset_index(drop=True, inplace=True)
#Mostrar el DataFrame.
result.head()

accuracy    recall  precision    fscore  \
0  0.997782  0.816176   0.973684  0.888000   
1  0.996118  0.757353   0.865546  0.807843   
2  0.976313  0.911765   0.301703  0.453382   
3  0.976313  0.911765   0.301703  0.453382   

                                modelo  
0                         RandomForest  
1                   LogisticRegression  
2  LogisticRegression_Sobre-balanceado  
3    LogisticRegression_Sub-balanceado

En el resumen se pueden visualizar las métricas para los modelos Random Forest y Logistic Regression, además de las variaciones Logistic Regression Sobre-balanceado y Logistic Regression Sub-balanceado. Donde se puede ver que el modelo que mejor se ajusta a los datos es Random Forest, pues es el más exacto, preciso, sensible y con mejor precisión de test. Por otro lado, el modelo Logistic Regression es un modelo alternativo menos preciso y sensible, por lo que algunos datos relevantes no serán bien calificados por este modelo. Por último, las variaciones de remuestreo sobre y sub balaceados de los datos aplicados al modelo Logistic Regression generan los mismos valores de métricas, aumentando la sensibilidad del modelo con un alto costo de precisión y presición del test. Por lo que, en este caso este procedimiento no mejora las métricas de Logistic Regression, si no que afecta en forma negativa la buena representatividad del modelo. Así Random Forest sigue siendo el mejor modelo.